version: "3"

services:
  
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
    environment:
      DSN: "postgres://artisan:artisan@postgres:5432/users"
    depends_on:
      - postgres

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - mongo

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=artisan
      - POSTGRES_PASSWORD=artisan
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: artisan
      MONGO_INITDB_ROOT_PASSWORD: artisan
    volumes:
      - ./db-data/mongo/:/data/db
