version: "3"

services:
  
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
    environment:
      DSN: "postgres://artisan:artisan@postgres:5432/users"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=artisan
      - POSTGRES_PASSWORD=artisan
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
